#!/bin/bash

# === Pedir datos al usuario ===
read -p "Introduce la IP para vmbr0 (ej: 172.26.0.222): " IP0
read -p "Introduce el Gateway para vmbr0 (ej: 172.26.0.1): " GW0
read -p "Introduce la IP para vmbr1 (ej: 10.0.0.222): " IP1

INTERFACES_FILE="/etc/network/interfaces"
BACKUP_FILE="${INTERFACES_FILE}.bak.$(date +%F-%H%M%S)"

# === Hacer copia de seguridad del archivo original ===
echo "📦 Guardando backup en: $BACKUP_FILE"
cp "$INTERFACES_FILE" "$BACKUP_FILE"

# === Escribir nueva configuración ===
cat > "$INTERFACES_FILE" <<EOF
# network interface settings; autogenerated
# Please do NOT modify this file directly, unless you know what
# you're doing.
#
# If you want to manage parts of the network configuration manually,
# please utilize the 'source' or 'source-directory' directives to do
# so.
# PVE will preserve these directives, but will NOT read its network
# configuration from sourced files, so do not attempt to move any of
# the PVE managed interfaces into external files!

auto lo
iface lo inet loopback

auto eth1
iface eth1 inet manual
        netmark 255.255.255.0

auto eth0
iface eth0 inet manual

auto bond0
iface bond0 inet manual
        bond-slaves eth0
        bond-miimon 100
        bond-mode balance-alb

auto bond1
iface bond1 inet manual
        bond-slaves eth1
        bond-miimon 100
        bond-mode balance-rr

auto vmbr0
iface vmbr0 inet static
        address $IP0/24
        gateway $GW0
        bridge-ports bond0
        bridge-stp off
        bridge-fd 0

auto vmbr1
iface vmbr1 inet static
        address $IP1/24
        bridge-ports bond1
        bridge-stp off
        bridge-fd 0
EOF

echo ""
echo "✅ Archivo de red escrito correctamente en $INTERFACES_FILE"
echo "🔁 Ejecuta ahora: 'ifreload -a' o reinicia Proxmox para aplicar los cambios"
